export const copyTraders = [
  {
    id: 1,
    nickname: "ProTraderX",
    name: "John Doe",
    winRate: 75,
    losses: 12,
    profitShare: 20.5,
    location: "New York",
    country: "US",
    strategy: "Day Trading",
    totalTrades: 300,
    followers: 1200,
    maxDrawdown: 8.2,
    favoriteStock: "AAPL",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 2,
    nickname: "SwingMaster",
    name: "Jane Smith",
    winRate: 62,
    losses: 8,
    profitShare: 15.2,
    location: "Los Angeles",
    country: "US",
    strategy: "Swing Trading",
    totalTrades: 450,
    followers: 800,
    maxDrawdown: 6.5,
    favoriteStock: "GOOGL",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 3,
    nickname: "OptionsPro",
    name: "Mike Johnson",
    winRate: 81,
    losses: 18,
    profitShare: 23.7,
    location: "London",
    country: "GB",
    strategy: "Options Trading",
    totalTrades: 250,
    followers: 1500,
    maxDrawdown: 7.1,
    favoriteStock: "TSLA",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 4,
    nickname: "Quantum master 🥂",
    name: "Sarah Williams",
    winRate: 68,
    losses: 15,
    profitShare: 18.9,
    location: "San Francisco",
    country: "US",
    strategy: "Forex Trading",
    totalTrades: 380,
    followers: 1000,
    maxDrawdown: 6.8,
    favoriteStock: "MSFT",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 5,
    nickname: "CryptoMaster",
    name: "Robert Brown",
    winRate: 73,
    losses: 10,
    profitShare: 21.3,
    location: "Sydney",
    country: "AU",
    strategy: "Cryptocurrency Trading",
    totalTrades: 320,
    followers: 900,
    maxDrawdown: 7.5,
    favoriteStock: "BTC",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 6,
    nickname: "CommoditiesExpert",
    name: "Emily Jones",
    winRate: 79,
    losses: 9,
    profitShare: 19.8,
    location: "Zurich",
    country: "CH",
    strategy: "Commodities Trading",
    totalTrades: 310,
    followers: 1100,
    maxDrawdown: 6.2,
    favoriteStock: "GLD",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 7,
    nickname: "OptionsWizard",
    name: "David White",
    winRate: 70,
    losses: 14,
    profitShare: 17.6,
    location: "Seattle",
    country: "US",
    strategy: "Options Trading",
    totalTrades: 270,
    followers: 850,
    maxDrawdown: 8.0,
    favoriteStock: "AMZN",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 8,
    nickname: "DayTradeQueen",
    name: "Linda Garcia",
    winRate: 76,
    losses: 11,
    profitShare: 22.0,
    location: "Singapore",
    country: "SG",
    strategy: "Day Trading",
    totalTrades: 290,
    followers: 1300,
    maxDrawdown: 7.3,
    favoriteStock: "NFLX",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 9,
    nickname: "SwingKing",
    name: "William Clark",
    winRate: 64,
    losses: 13,
    profitShare: 16.4,
    location: "Philadelphia",
    country: "US",
    strategy: "Swing Trading",
    totalTrades: 360,
    followers: 950,
    maxDrawdown: 6.6,
    favoriteStock: "AAPL",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 10,
    nickname: "ForexqueenX",
    name: "Karen Martinez",
    winRate: 72,
    losses: 17,
    profitShare: 20.2,
    location: "Berlin",
    country: "DE",
    strategy: "Forex Trading",
    totalTrades: 330,
    followers: 1400,
    maxDrawdown: 7.7,
    favoriteStock: "EURUSD",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 11,
    nickname: "Forex empress💃🥰",
    name: "Yuki Tanaka",
    winRate: 78,
    losses: 9,
    profitShare: 21.5,
    location: "Tokyo",
    country: "JP",
    strategy: "Day Trading",
    totalTrades: 280,
    followers: 1100,
    maxDrawdown: 7.8,
    favoriteStock: "JPY",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 12,
    nickname: "Cryptoxavant",
    name: "Raj Patel",
    winRate: 65,
    losses: 16,
    profitShare: 18.7,
    location: "Mumbai",
    country: "IN",
    strategy: "Swing Trading",
    totalTrades: 320,
    followers: 900,
    maxDrawdown: 6.4,
    favoriteStock: "INR",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 13,
    nickname: "Samba_trader",
    name: "Maria Silva",
    winRate: 73,
    losses: 12,
    profitShare: 20.1,
    location: "Sao Paulo",
    country: "BR",
    strategy: "Forex Trading",
    totalTrades: 340,
    followers: 1000,
    maxDrawdown: 7.1,
    favoriteStock: "BRL",
    image: "/assets/nellyaran.jpg",
    verified: false,
  },
  {
    id: 14,
    nickname: "Pyramidmystic 🔥",
    name: "Ahmed Mohamed",
    winRate: 80,
    losses: 10,
    profitShare: 22.3,
    location: "Cairo",
    country: "EG",
    strategy: "Cryptocurrency Trading",
    totalTrades: 270,
    followers: 1200,
    maxDrawdown: 7.6,
    favoriteStock: "BTC",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
  {
    id: 15,
    nickname: "Lucha$trader",
    name: "Luis Hernandez",
    winRate: 67,
    losses: 14,
    profitShare: 17.9,
    location: "Mexico City",
    country: "MX",
    strategy: "Day Trading",
    totalTrades: 310,
    followers: 1100,
    maxDrawdown: 7.0,
    favoriteStock: "MXN",
    image: "/assets/nellyaran.jpg",
    verified: true,
  },
];
