import "./globals.css";
import "./camera.css";
import "./styles.css";
import "animate.css";
import "aos/dist/aos.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import { Poppins } from "next/font/google";
import Navbar from "../components/main/navbars/Navbar";

const font = Poppins({ subsets: ["latin"], weight: ["300"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className="fixed top-0 left-0 w-full text-white z-30 ">
          <Navbar />
        </div>
        {children}
      </body>
    </html>
  );
}
